window:
  decorations: None
  opacity: 0.85

scrolling:
  multiplier: 5

font:
  normal:
    family: DankMono Nerd Font Mono
    style: Regular
  bold:
    family: DankMono Nerd Font Mono
    style: Bold
  italic:
    family: DankMono Nerd Font Mono
    style: Italic
  size: 17.8 

draw_bold_text_with_bright_colors: true

cursor:
    style:
        blinking: Always
        blink-interval: 900

env:
  TERM: xterm-256color

# horizon
#colors:
  ## Primary colors
  #primary:
    #background: '0x1c1e26'
    #foreground: '0xe0e0e0'

    ## Normal colors
  #normal:
    #black: '0x16161c'
    #red: '0xe95678'
    #green: '0x29d398'
    #yellow: '0xfab795'
    #blue: '0x26bbd9'
    #magenta: '0xee64ac'
    #cyan: '0x59e1e3'
    #white: '0xd5d8da'

    ## Bright colors
  #bright:
    #black: '0x5b5858'
    #red: '0xec6a88'
    #green: '0x3fdaa4'
    #yellow: '0xfbc3a7'
    #blue: '0x3fc4de'
    #magenta: '0xf075b5'
    #cyan: '0x6be4e6'
    #white: '0xd5d8da'

#key_bindings:
  #- { key: Back, mods: Super, chars: "\x15" }

colors:
  primary:
    background: '#1c2029'
    foreground: '#d8dee9'
    dim_foreground: '#a5abb6'
  cursor:
    text: '#2e3440'
    cursor: '#d8dee9'
  vi_mode_cursor:
    text: '#2e3440'
    cursor: '#d8dee9'
  selection:
    text: CellForeground
    background: '#4c566a'
  search:
    matches:
      foreground: CellBackground
      background: '#88c0d0'
    bar:
      background: '#434c5e'
      foreground: '#d8dee9'
  normal:
    black: '#3b4252'
    red: '#bf616a'
    green: '#a3be8c'
    yellow: '#ebcb8b'
    blue: '#81a1c1'
    magenta: '#b48ead'
    cyan: '#88c0d0'
    white: '#e5e9f0'
  bright:
    black: '#4c566a'
    red: '#bf616a'
    green: '#a3be8c'
    yellow: '#ebcb8b'
    blue: '#81a1c1'
    magenta: '#b48ead'
    cyan: '#8fbcbb'
    white: '#eceff4'
  dim:
    black: '#373e4d'
    red: '#94545d'
    green: '#809575'
    yellow: '#b29e75'
    blue: '#68809a'
    magenta: '#8c738c'
    cyan: '#6d96a5'
    white: '#aeb3bb'

key_bindings:
#xxd -psd
    # ctrl+b n
    - { key: K,     mods: Command|Shift, chars: "\x02\x6e" }
    # ctrl+b p
    - { key: J,     mods: Command|Shift, chars: "\x02\x70" }

    # ctrl+b %
    - { key: L,     mods: Command|Shift, chars: "\x02\x25" }
    # ctrl+b "
    - { key: H,     mods: Command|Shift, chars: "\x02\x22" }

    # ctrl+b x
    - { key: H,     mods: Command|Shift, chars: "\x02\x78" }

    # ctrl+b %
    # vim
    - { key: H,     mods: Command,       chars: "\x08" }
    - { key: L,     mods: Command,       chars: "\x0c" }
    - { key: J,     mods: Command,       chars: "\x0a" }
    - { key: K,     mods: Command,       chars: "\x0b" }
    - { key: D,     mods: Command,       chars: "\x04" }
    - { key: C,     mods: Command,       chars: "\x02\x63" }
    - { key: Space,  mods: Shift,  action: ToggleViMode }
