#!/bin/bash

# RUN WITH 
#   `bash copy` zippin stuff up to ~/Downloads/tmp-files.zip
#   `bash copy setup` below + setting up stuff
#   `bash copy <any-argument>` unzippin stuff from ~/Downloads/tmp-files.zip

args=("$@")

# zipping up
if [ $# -eq 0 ]
    then
        echo "cleaning up"
        rm -rf ~/tmp-files/*
        mkdir -p ~/tmp-files


        echo "movin stuff"
        cp ~/.alacritty.yml ~/tmp-files/.alacritty.yml
        cp -R ~/.tmux.conf ~/tmp-files/.tmux.conf
        cp ~/.vimrc ~/tmp-files/.vimrc
        cp ~/.zshrc ~/tmp-files/.zshrc
        cp ~/settings.json ~/tmp-files/settings.json
        cp ~/.brew ~/tmp-files/.brew

        echo "inception"
        cp ~/copy ~/tmp-files/copy

        echo "movin directories"
        mkdir ~/tmp-files/.tmux
        cp -R ~/.tmux ~/tmp-files
        mkdir ~/tmp-files/.vim
        cp ~/.vim/coc-settings.json ~/tmp-files/.vim/coc-settings.json

        echo "delete all other than most recent bttpreset, copy to tmp-file "
        ls -t  ~/Downloads/*.bttpreset | tail -n +2 | xargs rm -f
        find ~/Downloads -type f -name "*.bttpreset" -maxdepth 1 -exec cp "{}" ~/tmp-files/$(date +"%m-%d-%y").bttpreset \;


        echo "skip personal"
        #cp ~/Derek.bettertouchtool ~/tmp-files/Derek.bettertouchtool
        #cp ~/DankMono-Regular.otf ~/tmp-files/DankMono-Regular.otf
        #cp ~/DankMono-Italic.otf ~/tmp-files/DankMono-Italic.otf
        #mkdir -p ~/tmp-files/.config/tmuxinator
        #cp -R ~/.config/tmuxinator ~/tmp-files/.config



        echo "cleaning up"
        cd ~/tmp-files
        zip -r -FS ~/tmp-files.zip .
        cp ~/tmp-files.zip ~/Downloads/tmp-files.zip
        rm -rf ~/tmp-files
        echo "done!"
        echo "file created in ~/Downloads/tmp-files.zip"
else
#   test
#   rm -rf ~/tmp-files
#   mkdir ~/tmp-files
#   unzip ~/Downloads/tmp-files.zip -d ~/tmp-files

    function unzippem() {
        echo "unzippin to ~/ root directory"
        unzip -o ~/Downloads/tmp-files.zip -d ~
    }

    if [ $1 = "setup" ]
        then
            echo "setting up for the first time"
            echo "setting homebrew"
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
            for a in $(cat .brew); do brew list $a || brew install $a; done


            echo "installing .bttpreset"
            ls -t  ~/*.bttpreset | tail -n +1 | xargs open

            echo "installing fonts"
            ls -t  ~/*.otf | tail -n +1 | xargs open
            unzippem

            echo "keyboard stuff"
            defaults write -g InitialKeyRepeat -int 10 
            #   normal minimum is 15 (225 ms)
            defaults write -g KeyRepeat -int 1 
            #   normal minimum is 2 (30 ms)
            defaults write -g ApplePressAndHoldEnabled -bool false


    elif [[ $1 == *"paste"* ]]
        then
            rm ~/*.bttpreset
            #mkdir -p ~/tmp-files & unzip -o ~/Downloads/tmp-files.zip -d ~/Downloads/tmp-files
            unzippem

            # vim command: do (other into current) / dp (current into other)
            for files in $(diff -rq ~ ~/Downloads/tmp-files|grep 'differ$'|sed "s/^Files //g;s/ differ$//g;s/ and /:/g"); do
                vimdiff ${files%:*} ${files#*:};
            done

    elif [[ $1 == *"dotfile"* ]] 
        # need to use '. ./copy dotfiles' with double [[ for current path to cd
        then
            echo "finding path"
            for DIR in $(find ~/Desktop -type d -name "dotfiles")
                do   
                    unzip -o ~/Downloads/tmp-files.zip -d "$DIR"
                    cd $DIR
                    gacp "update"
                done
    fi

fi
