#!/bin/bash

# RUN WITH 
#   `bash copy` zippin stuff up to ~/Downloads/tmp-files.zip
#   `bash copy setup` below + setting up stuff
#   `bash copy <any-argument>` unzippin stuff from ~/Downloads/tmp-files.zip

args=("$@")

# zipping up
if [ $# -eq 0 ]
    then
        echo "cleaning up"
        rm -rf ~/tmp-files/*
        mkdir -p ~/tmp-files

        echo "movin stuff"
        cp ~/.alacritty.yml ~/tmp-files/.alacritty.yml
        cp -R ~/.tmux.conf ~/tmp-files/.tmux.conf
        cp ~/.vimrc ~/tmp-files/.vimrc
        cp ~/.zshrc ~/tmp-files/.zshrc
        cp ~/settings.json ~/tmp-files/settings.json
        cp ~/.brew ~/tmp-files/.brew

        echo "inception"
        cp ~/copy ~/tmp-files/copy

        echo "movin directories"
        mkdir ~/tmp-files/.tmux
        cp -R ~/.tmux ~/tmp-files
        mkdir -p ~/tmp-files/.config/tmuxinator
        cp -R ~/.config/tmuxinator ~/tmp-files/.config
        mkdir ~/tmp-files/.vim
        cp ~/.vim/coc-settings.json ~/tmp-files/.vim/coc-settings.json

        echo "downloadin cvim"
        git clone https://gist.github.com/4e03d5828cce47d42d54f9c5507479d1.git cvim
        mkdir ~/tmp-files/cvim
        cp -R ~/cvim/.cVimrc ~/tmp-files/cvim/.cVimrc
        cp -R ~/cvim/cvim.css ~/tmp-files/cvim/cvim.css

        echo "delete all other than most recent bttpreset, copy to tmp-file "
        ls -t  ~/Downloads/*.bttpreset | tail -n +2 | xargs rm -f
        find ~/Downloads -type f -name "*.bttpreset" -maxdepth 1 -exec cp "{}" ~/tmp-files/$(date +"%m-%d-%y").bttpreset \;

        echo "cleaning up"
        cd ~/tmp-files
        zip -r -FS ~/tmp-files.zip .
        cp ~/tmp-files.zip ~/Downloads/tmp-files.zip
        rm -rf ~/tmp-files
        echo "done!"
        echo "file created in ~/Downloads/tmp-files.zip"

#       cp ~/DankMono-Regular.otf ~/tmp-files/DankMono-Regular.otf
#       cp ~/DankMono-Italic.otf ~/tmp-files/DankMono-Italic.otf
#       cp ~/Derek.bettertouchtool ~/tmp-files/Derek.bettertouchtool

else
#   test
#   rm -rf ~/tmp-files
#   mkdir ~/tmp-files
#   unzip ~/Downloads/tmp-files.zip -d ~/tmp-files

    if [ $1="setup" ]
        then
            echo "setting up for the first time"
            echo "setting homebrew"
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
            for a in $(cat .brew); do brew list $a || brew install $a; done


            echo "installing .bttpreset"
            ls -t  ~/*.bttpreset | tail -n +1 | xargs open

            echo "installing fonts"
            ls -t  ~/*.otf | tail -n +1 | xargs open
    fi

    echo "unzippin to ~/ root directory"
    unzip -o ~/Downloads/tmp-files.zip -d ~
fi
